### ISSUE TITLE
CV Generator 

### ISSUE THREAD

**Issue by Thetribunalcode** [Tenet-Coding/Hacktoberfest-Projects#102]
# Description : 
A simple CV Generator with customizable text. Users on the landing page will be asked for inputs like

1. Name and other details
2. Skillset 
3. Work Experience ( If any )
4. Achievements / Certifications
5. Languages and other interests/hobbies

After this, the inputs will be slotted into a presentable and professional-looking CV. 

## Features :
- A very noncoder-friendly interface ( Users do not have to manually change HTML but instead just fill a form.)
- Professional and presentable CV will be generated

---
**Tentative Deadline: 4 days**

**Comment by soumik2012** [comment]
Go ahead @Thetribunalcode 💯

**Comment by soumik2012** [comment]
@Thetribunalcode Are going to do this issue or not ??

**Comment by smabbett** [comment]
Is this still open?
