### ISSUE TITLE
Project: Joke Generator

### ISSUE THREAD

**Issue by SandeepKrSuman** [Tenet-Coding/Hacktoberfest-Projects#114]
# Description :
A web page to generate a random joke on every click.

## Features :
- Fetch and display random jokes on click

---
**Tentative Deadline : 1 day**

**Comment by 5h15h1r** [comment]
@SandeepKrSuman  can you assign this to me, also do i get 24 hours only??

**Comment by pavankalyan-codes** [comment]
Hey! @SandeepKrSuman Made a PR for this project. pls review the PR and merge it if everything looks fine. #115

**Comment by SandeepKrSuman** [comment]
Hey @5h15h1r the assignment process is done by the project maintainers, I'm **not** one of them. 
Also I have opened this issue to be assigned to myself. You can open a new issue and start working on it when it is assigned to you.

**Comment by pavankalyan-codes** [comment]
Sorry I thought you were owner of this repo @SandeepKrSuman. Will read contributing guidelines.

**Comment by soumik2012** [comment]
@SandeepKrSuman You can work on the issue.
