### ISSUE TITLE
Snake Game in Python

### ISSUE THREAD

**Issue by Thetribunalcode** [Tenet-Coding/Hacktoberfest-Projects#120]
# Description :
The snake game in python

## Features :
- The classic snake game, coded in python

---
**Tentative Deadline : 1 days (Provide tentative deadline as per your analyses. Make sure it falls under 1st Oct to 31st Oct)**

**Comment by Abhishek91520** [comment]
Can I Contribute ?

**Comment by Thetribunalcode** [comment]
Thank you
