### ISSUE TITLE
BALL-PADDDLE GAME

### ISSUE THREAD

**Issue by 2devyank** [Tenet-Coding/Hacktoberfest-Projects#126]
# Description :
This is the vintage game which everyone used to play in thier childhood i.e ball will hit the brick and brick will be destroyed , then it will fall back to the paddle if you failed to make contact between them then you will lose one life

## Features :
- Point Down some creative features ! 
Canvas will be used to make this game

**Comment by soumik2012** [comment]
Great project @2devyank love to see your PR 👍🏻
