### ISSUE TITLE
Project : Background Colour Changer 

### ISSUE THREAD

**Issue by Harshil-Jani** [Tenet-Coding/Hacktoberfest-Projects#13]
Create a Web Page with some text, color and button also add your own creativity.

General Expectations : 

- If you click on button then Background color must change.
- Make the web page mobile responsive as well.
- Atleast take 4 to 5 new colors.

**Project will be assigned on First come First Serve basis after October 1**

**Comment by prabincankod** [comment]
Assign this to me. I can make a random background color changer.

**Comment by BajraYeJoon** [comment]
Simple Background Change Color page has been committed. Please review the PR. 😊😊

**Comment by Harshil-Jani** [comment]
> Simple Background Change Color page has been committed. Please review the PR. blushblush

@BajraYeJoon Hey ! Next time ask maintainers to assign you the issue before PR.
We will be serving on First Come First Serve Basis. And this will help you in Open Source Journey Further as well.

Happy Hactoberfest :tada:
