### ISSUE TITLE
Project : Word Counter

### ISSUE THREAD

**Issue by Harshil-Jani** [Tenet-Coding/Hacktoberfest-Projects#14]
General Requirements : 
- Create a word Counter.
-  It should count the exact number of words written on an element.
- You can implement in Any form.
- Be little more creative.

**Project Issues will be assigned on First Come First Serve Basis after October 1**

**Comment by KaveenLaksitha** [comment]
Hi... I'm new to open source. Can I contribute to this issue?. I think I can do it.

**Comment by soumik2012** [comment]
@KaveenLaksitha go ahead 🕺

**Comment by KaveenLaksitha** [comment]
@soumik2012 Thanks. If you don't mind, can you tell me how to start?

**Comment by soumik2012** [comment]
#### Step to Contribute 
- Fork this repository
- Clone the repository in your computer 
- Create a branch ```projectname-username-branch```
- Add your projects to a new directory, the name of the directory should be your ```Word_Counter``
- Add ```One project``` at a time
- Add & commit
- Push changes to GitHub
- Compare & Submit a Pull Request

**Comment by KaveenLaksitha** [comment]
@soumik2012 Thanks

**Comment by SudhansuuRanjan** [comment]
I want to contribute on it.

**Comment by KaveenLaksitha** [comment]
@soumik2012 I've submitted a pull request.

**Comment by KaveenLaksitha** [comment]
@soumik2012  task is completed and pr ready to merge.
