### ISSUE TITLE
Project : Rock, Paper, Scissors 🪨  ✂️ 🧻 

### ISSUE THREAD

**Issue by soumik2012** [Tenet-Coding/Hacktoberfest-Projects#16]
General Requirements : 
- Create a Rock, Paper, Scissors.
- You can implement in Any form.
- Be little more creative.

**Project Issues will be assigned on First Come First Serve Basis after October 1**

**Comment by nshanbhag20001412** [comment]
hey i would like to work on this. Can you assign it to me?

**Comment by soumik2012** [comment]
@nshanbhag20001412 Go head 👍🏻

**Comment by nshanbhag20001412** [comment]
Okay so Ill be making a web app using JS-HTML-CSS. I wanted to ask about the folder creation. 

#### So I'm expected to create a folder named Rock-Paper-Scissors like the image below and then put my code in it right?
![image](https://user-images.githubusercontent.com/63840903/134810478-bfe8d4af-02d7-4819-b593-b1db7c7e68e8.png)

**Comment by soumik2012** [comment]
@nshanbhag20001412 That's right.

**Comment by vish-han** [comment]
Can i also made the rock paper scissors game??

**Comment by 2devyank** [comment]
I would like to work on this issue also please assign me .

**Comment by nshanbhag20001412** [comment]
@soumik2012 I'm done with this project . I'll be sending a PR tomorrow.

**Comment by soumik2012** [comment]
Okay @nshanbhag20001412 thank you for update!!
