### ISSUE TITLE
Project :  Weather Forecast ⛈️ 

### ISSUE THREAD

**Issue by soumik2012** [Tenet-Coding/Hacktoberfest-Projects#17]
Make an application to predict the state of the atmosphere for a given location.
General Requirements :

- Create Toss, Either as a web page (More Preffered) or as Programming languages.
- An input for users to type city name
- Display current weather including weather condition, temperature, humidity, wind speed, and date and time
- Visualization to display the temperature change, humidity change, and weather conditions of each day
- Try to make GUI if you work with other programming languages.
- Show some of your creativity.

**Project Issues will be assigned on First Come First Serve basis after 1st October**

**Comment by SudhansuuRanjan** [comment]
Hello... I'm a beginner. Can I contribute to this issue?.

**Comment by Jisan129** [comment]
Can I use express framework to do this?

**Comment by BajraYeJoon** [comment]
it would be great if you assigned me this project. Will be helpful for me to excel on my current Js skills

**Comment by soumik2012** [comment]
@Jisan129 and @BajraYeJoon  As I mentioned **First Come First Serve basis** you can create the issue or you can see the other issue.

**Comment by BajraYeJoon** [comment]
@soumik2012 Please review PR . If there is any issue regarding it, please guide me through it. thank you 😊

**Comment by BajraYeJoon** [comment]
@soumik2012  Please review the new and updated PR 😃
