### ISSUE TITLE
Project : Guess the Bollywood Movies  With Emoji 🎟🎞

### ISSUE THREAD

**Issue by soumik2012** [Tenet-Coding/Hacktoberfest-Projects#22]
Make an application to Gusse the Bollywood Movies with emojis 
General Requirements :
- Create a web page for this game 
-  User should decide guessing time _(10 - 30 sec )_
-  Show some of your creativity.

**Project Issues will be assigned on First Come First Serve basis after 1st October**

**Comment by K-ash-ish** [comment]
Hey, can I work on this project? I'll be making this with HTML, CSS, and JS.

**Comment by Harshil-Jani** [comment]
> Hey, can I work on this project? I'll be making this with HTML, CSS, and JS.

@K-ash-ish Sure ! Go Ahead.
Happy Hacktoberfest :tada:

**Comment by K-ash-ish** [comment]
I'm doing it for the first time. So after forking and cloning, I have to make a folder with the name of the project and then put my files there and make a PR after 1 OCT.

**Comment by soumik2012** [comment]
Yay @K-ash-ish

**Comment by sam-cody** [comment]
HI! i wolud like to work on it. can you assign to me?

**Comment by Harshil-Jani** [comment]
> HI! i wolud like to work on it. can you assign to me?

It's Already assigned. You can create new issue for some another project idea which don't already exist here.

**Comment by Harshil-Jani** [comment]
@K-ash-ish Plz let us know your status with the project ! If you are facing any issues or something we can help.

**Comment by K-ash-ish** [comment]
@Harshil-Jani  I completed the frontend part. I'm having some issues with dom-manipulation of getting answers from users. I'm new to DOM manipulation give me some more time I'll finish it within 2 days. Sorry I didn't report the status of the project I'm new to this.

**Comment by Harshil-Jani** [comment]
> @Harshil-Jani I completed the frontend part. I'm having some issues with dom-manipulation of getting answers from users. I'm new to DOM manipulation give me some more time I'll finish it within 2 days. Sorry I didn't report the status of the project I'm new to this.

No worries ! Take your time. Just keep updating after 2-3 days so we would know the project track.

**Comment by K-ash-ish** [comment]
Ok I will report the status.

**Comment by K-ash-ish** [comment]
hey, @Harshil-Jani   I completed most of the part only some styling is remaining. I want to ask I have to give the user a particular time for the overall quiz or for each question?

**Comment by K-ash-ish** [comment]
@Harshil-Jani  hey sorry to disturb you but I did a small mistake I deleted the project folder from my computer I was deleting some other file. So, if I commit again will it show entire files changes or the changes you asked for.

**Comment by Harshil-Jani** [comment]
> @Harshil-Jani hey sorry to disturb you but I did a small mistake I deleted the project folder from my computer I was deleting some other file. So, if I commit again will it show entire files changes or the changes you asked for.

I would suggest you to clone your fork on your local system again (delete older one in case still left). So, You don't lose up any of your commits and make the requested changes on that files and push them back to same branch by which you had opened PR so it won't interefere anywhere in workflow.

**Comment by Harshil-Jani** [comment]
> hey, @Harshil-Jani I completed most of the part only some styling is remaining. I want to ask I have to give the user a particular time for the overall quiz or for each question?

Both way ! It works. It entirely depends on your logic. Prefer for each question, but if even if it's whole game then too it's fine.

**Comment by K-ash-ish** [comment]
I'm unable to do the timer work.
