### ISSUE TITLE
Project : Landing Page

### ISSUE THREAD

**Issue by Sugyanee** [Tenet-Coding/Hacktoberfest-Projects#25]
- A Landing page: Using HTML, CSS, and Javascript

**Comment by Sugyanee** [comment]
@soumik2012  Do assign me

**Comment by Harshil-Jani** [comment]
@Sugyanee Yes, You can go ahead. Try to show you creativity with your tech stacks.
Make Sure you PR this project after 1st Oct.
Happy Hacktoberfest :tada:

**Comment by sam-cody** [comment]
hi! can i work on it?

**Comment by sam-cody** [comment]
@Harshil-Jani  can you assign me?

**Comment by mr-shubhams** [comment]
Hi' can I work on it?

**Comment by Harshil-Jani** [comment]
@Sugyanee Can you update us regarding the project ? If you are not working on it then we can assign it to others !

**Comment by Sugyanee** [comment]
> @Sugyanee Can you update us regarding the project ? If you are not working on it then we can assign it to others !

I am working on it and will complete it by tomorrow most probably

**Comment by Harshil-Jani** [comment]
> > @Sugyanee Can you update us regarding the project ? If you are not working on it then we can assign it to others !
> 
> I am working on it and will complete it by tomorrow most probably

Sure ! No worries take your time. We just needed timely update regarding project track.

**Comment by Sugyanee** [comment]
> > > @Sugyanee Can you update us regarding the project ? If you are not working on it then we can assign it to others !
> > 
> > 
> > I am working on it and will complete it by tomorrow most probably
> 
> Sure ! No worries take your time. We just needed timely update regarding project track.

I have created the pull request . Do check
