### ISSUE TITLE
Project : Notepad 

### ISSUE THREAD

**Issue by siddhantkhariwal** [Tenet-Coding/Hacktoberfest-Projects#27]
**DESCRIPTION**:  Make a notepad website that saves notes in localStorage.

**GENERAL REQUIREMENTS:**

Create a website with good design and visuals.
Add delete button for deleting notes from local storage.

**USE CASE:**
Users can create notes and delete them.

**ADDITIONAL CHALLENGES :** 
Create a search button so that users can search notes.

**Comment by siddhantkhariwal** [comment]
@Harshil-Jani Please do assign me.

**Comment by Harshil-Jani** [comment]
@siddhantkhariwal Go Ahead !
Happy Hacktoberfest :tada:

**Comment by 7suyash7** [comment]
Hey @Harshil-Jani I have created this project please assign it to me, so I can submit it :)

**Comment by siddhantkhariwal** [comment]
Hello, @soumik2012  and  @Harshil-Jani I have created a pull request, kindly see through it.
