### ISSUE TITLE
News App 

### ISSUE THREAD

**Issue by omrawal** [Tenet-Coding/Hacktoberfest-Projects#29]
Can I create a news app on Flask Using the news API available?

**Comment by Harshil-Jani** [comment]
Sure ! Show your Hacktoberfest Creativity :tada:

**Comment by Harshil-Jani** [comment]
@omrawal Any further updates on the project ?

**Comment by omrawal** [comment]
I m very close to completion but this week I have my College Exams so is it okay if I complete and create a pull request on 9th Oct i.e. Saturday

**Comment by Harshil-Jani** [comment]
@omrawal No issues. Just commit few changes at your free time once before 9th Oct and tag us here. So we can see project track on your fork itself. Take your time !
