### ISSUE TITLE
Project: Spotify Clone

### ISSUE THREAD

**Issue by sanskruti-shahu** [Tenet-Coding/Hacktoberfest-Projects#34]
Description :
This will be spotify clone with most of spotify's features. 
Using html, CSS and React.

**Comment by RajshreeVats** [comment]
Hey, can I work on this issue?

**Comment by soumik2012** [comment]
Go ahead @sanskruti-shahu  💯

**Comment by soumik2012** [comment]
> Hey, can I work on this issue?



> Hey, can I work on this issue?

You can look at another issue or make a new issue if you want ...

**Comment by soumik2012** [comment]
Any updates ??

**Comment by sanskruti-shahu** [comment]
Yaa.. I am working on it. It will take 3-4 days more.
