### ISSUE TITLE
Project : Math Chaos

### ISSUE THREAD

**Issue by RepeaterCreeper** [Tenet-Coding/Hacktoberfest-Projects#35]
# Description :
Improve your math skills while enjoying your time! Keep track of your progress. 

## Features :
- 🏆 **Leaderboard** - leaderboard is provided by local sessions.
- ⚡ **Lightning Mode** - solve each math problem as fast as you can.
   - Addition, Subtraction, Multiplication, and Division are all included.
 

## Setup :
Not yet implemented.

---

**Tentative Deadline : October 10th**

**Comment by Harshil-Jani** [comment]
@RepeaterCreeper Go Ahead ! Nice Idea :tada:

**Comment by soumik2012** [comment]
Any updates ??

**Comment by RepeaterCreeper** [comment]
Yeah, I'm struggling with the design. Do you want me to upload the unfinished version?

**Comment by soumik2012** [comment]
@RepeaterCreeper no need to upload the unfinished version

**Comment by RepeaterCreeper** [comment]
@Harshil-Jani  I have it completed. I've made the pull request.
