### ISSUE TITLE
Project: Dark Mode Option In a Web Page

### ISSUE THREAD

**Issue by BajraYeJoon** [Tenet-Coding/Hacktoberfest-Projects#45]
# Description :

A simple web page with a dark mode toggle that will have two option : light mode and dark mode.

## Features :
- User can have light mode turned on as well as dark mode

---
**Tentative Deadline :  1 days (Provide tentative deadline as per your analyses. Make sure it falls under 1st Oct to 31st Oct)**

## Some Rules to follow :
- Add a README.md file for your project.
- Name of Project
- Demo of Project in .gif how your project is look
- Description of project
- Requirements or Setup instructions
- Name of Author(s)
- Look at [Demo](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/ConwaysGameOfLife/README.md) here.

**Comment by BajraYeJoon** [comment]
@Harshil-Jani @Rameshchandrapola @soumik2012  Can you assign me this for the next project that I want to do for the hacktoberfest ?

**Comment by arpan-pro-learner** [comment]
it seems good and interesting to me can I work on this 🤔

**Comment by Harshil-Jani** [comment]
@BajraYeJoon Go Ahead ! :tada:
Happy Hacktoberfest :rocket:

**Comment by BajraYeJoon** [comment]
@Harshil-Jani  Please review the PR.😃

**Comment by Mark-42-max** [comment]
Hello! I would like to contribute to the issue. Would you assign the issue to me?
