### ISSUE TITLE
Update the Readme.md File

### ISSUE THREAD

**Issue by soumik2012** [Tenet-Coding/Hacktoberfest-Projects#5]
Add few lines to the readme.md like 
Headline - # Step to Contribute 
-  How to create a pull request  with some 
- Steps to contribute
- Fork this repository
- Clone the repository
- Create a branch ```projectname-username-branch```
- Add your projects to a new directory, the name of the directory should be your ```ProjectName/USERNAME```
- Add ```One project``` at a time
- Add & commit
- Push changes to GitHub
- Compare & Submit a Pull Request
- Leave a ⭐ if you liked working on the project.

**Comment by Rameshchandrapola** [comment]
Can I update Readme.md file as your requirements ???

**Comment by Harshil-Jani** [comment]
Yes @Rameshchandrapola  Go Ahead ! :tada:
