### ISSUE TITLE
Shades-colorGenerator

### ISSUE THREAD

**Issue by Ukesh-dev** [Tenet-Coding/Hacktoberfest-Projects#51]
# Description :
A website for generating the different shades of colors.
## Features :
- Having the funtionality to copy the selected colors to clipboard. 
- Made using Reactjs.

**Comment by Ukesh-dev** [comment]
@soumik2012  Please assign it to me.

**Comment by Harshil-Jani** [comment]
@Ukesh-dev We have already one project named as Background_Color_Changer that serves the similar purpose ! Try something different

**Comment by Harshil-Jani** [comment]
@Ukesh-dev Go Ahead ! Just Once go through Background Color Changer project from the repo and make sure your project outcome don't conflict with that.  !
Instill your creativity as well.:rocket:
