### ISSUE TITLE
Project: Dice rolling game

### ISSUE THREAD

**Issue by Rameshchandrapola** [Tenet-Coding/Hacktoberfest-Projects#52]
# Description : Dice rolling game of two players

## Features :
- Two players will throw two dice randomly, then the result will be declared based on the score on each player dice.

---
**Tentative Deadline: 2 days (Provide tentative deadline as per your analyses. Make sure it falls under 1st Oct to 31st Oct)**

**Comment by Harshil-Jani** [comment]
Go Ahead :rocket:

**Comment by cosmoimai** [comment]
can you assign me this sir?
