### ISSUE TITLE
Update the Readme.md 

### ISSUE THREAD

**Issue by soumik2012** [Tenet-Coding/Hacktoberfest-Projects#56]
Add the Hall of frames in our readme.MD like this - 
 
![image](https://user-images.githubusercontent.com/66599363/135738189-dd6dbdb2-ac32-48d4-aa46-63538f09c1d7.png)

**Comment by jeetsdev** [comment]
Can you assign it to me? I can work on this. @soumik2012

**Comment by TasinAhmed** [comment]
Hey @soumik2012 I would like to work on this

**Comment by TasinAhmed** [comment]
Oh nvm. Go ahead @jeetsdev

**Comment by jeetsdev** [comment]
Hey, buddy @soumik2012, I was trying to implement this feature using sourcerer.io but I am not able to add it. Can you help me with some resources or do I have to hardcode all the contributor's names?

**Comment by jeetsdev** [comment]
I figured it out. Opened a PR for the same.

**Comment by Mark-42-max** [comment]
I would like to take up the issue. Could I be assigned to it? @soumik2012
