### ISSUE TITLE
Project: MineSweeper Game

### ISSUE THREAD

**Issue by Ayush21042002** [Tenet-Coding/Hacktoberfest-Projects#57]
# Description :
The game is a simulation of the famous Minesweeper video game built using HTML, CSS and JS

## Features :
- Flag a cell
- Open a cell
- Restart your game after every win or loss.
- Every time bombs will be placed randomly. 

---
**Tentative Deadline : 2 days (Provide tentative deadline as per your analyses. Make sure it falls under 1st Oct to 31st Oct)**

## Some Rules to follow :
- Add a README.md file for your project.
- Name of Project
- Demo of Project in .gif how your project is look
- Description of project
- Requirements or Setup instructions
- Name of Author(s)
- Look at [Demo](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/ConwaysGameOfLife/README.md) here.

**Comment by Ayush21042002** [comment]
@soumik2012 i would like to work on this project so, can you assign this to me?

**Comment by swaraj-ssk** [comment]
Can you assign me this project ?

**Comment by Ayush21042002** [comment]
> @soumik2012 i would like to work on this project so, can you assign this to me?

@soumik2012 can i work on this project?

**Comment by soumik2012** [comment]
Go ahead @Ayush21042002 👍🏻
