### ISSUE TITLE
Project: Hacktoberfest Landing page ⏲⏳

### ISSUE THREAD

**Issue by BajraYeJoon** [Tenet-Coding/Hacktoberfest-Projects#71]
# Description :

This Landing page will feature the remaining time for the hacktoberfest 2021. 

## Features :
- Register Button ✅for the participant that will redirect to hacktoberfest official site
- Countdown timer ⏳

---
Tentative Deadline : 1day

**Comment by BajraYeJoon** [comment]
@Harshil-Jani @soumik2012  I came up with this new idea to contribute more, Can you please assign for the following issue? 😃🎉

**Comment by BajraYeJoon** [comment]
@soumik2012 @Harshil-Jani  Can you please assign me to this work ?😃🚀

**Comment by soumik2012** [comment]
The lading page is already made.
