### ISSUE TITLE
Project : Phone Number Validator

### ISSUE THREAD

**Issue by SANTHOSH17-DOT** [Tenet-Coding/Hacktoberfest-Projects#76]
# Description :
Phone Number validator app made with Javascript (using regex), HTML, CSS, and Bootstrap.

## Features :
- Glass morphism is used for frontend.

---
**Tentative Deadline : Completed

**Comment by pavankalyan-codes** [comment]
Hey can you pla assign thia to me. I'll work on it

**Comment by abhirv08-1** [comment]
@SANTHOSH17-DOT Please asssign it to me.

**Comment by SANTHOSH17-DOT** [comment]
@soumik2012 @Harshil-Jani Can you please assign me to this work ?
