### ISSUE TITLE
A journal app for making daily entries

### ISSUE THREAD

**Issue by VaithiSniper** [Tenet-Coding/Hacktoberfest-Projects#95]
# Description :
A simple MERN based journal app to allow the user to make daily entries, tag entries with labels and retrieve them as needed (filterable by date and label, or search word)

## Features :
- User can make entries with title (optional) and the actual entry. On submission, user can also add tags if necessary.
- The posts will be accumulated in db.
- User can retrieve previous entries by date, searching words in entries or tags/labels assigned by them previously. This will allow the user to create multiple entries in a day and sort them into different tags (if the user decides to vent about their work and personal life, they can have separate posts with different labels).
- A dashboard page where the recent entry will be briefly shown (Title fully with date and substringed content)
- Authentication so users can make accounts and use them to use login. This way their posts can stay safe.

---
**Tentative Deadline : 5 days (Provide tentative deadline as per your analyses. Make sure it falls under 1st Oct to 31st Oct)**

## Some Rules to follow :
- Add a README.md file for your project.
- Name of Project
- Demo of Project in .gif how your project is look
- Description of project
- Requirements or Setup instructions
- Name of Author(s)
- Look at [Demo](https://github.com/Tenet-Coding/Hacktoberfest-Projects/blob/master/ConwaysGameOfLife/README.md) here.

**Comment by VaithiSniper** [comment]
Can I work on this?

**Comment by VaithiSniper** [comment]
Similar yes, except it'll be more journal oriented. It's more like for personal use, to write and maintain a daily journal and obviously styling will be similar to a bullet journal. So the content will likely be more than a note app as well.
Also instead of the note app format where you can see all your previous notes on the board, you'll only be able to see your recent one on the account dashboard and for the rest, you'll have to go to a different route. So it's focused on being a journal where a person can see where they left off the prev day and continue that with that day's entry. But yes, you can also see prev entries.

**Comment by Harshil-Jani** [comment]
@VaithiSniper Cool ! Sounds Great 💯  Go Ahead 🎉

**Comment by VaithiSniper** [comment]
Thank you!
